### ISSUE TITLE
Mobile, impossible to hide the popup.

### ISSUE THREAD

**Issue by Vesli** [TyMaszWeb/django-cookie-law#14]
Hi,

Thanks for this plugin ;)

On Safari / Chrome (iOS) or Android Chrome, I can click as many time as I want, the popup will always come back.

On the other hand, sometimes it won't show, I will wait 3min, reload the home page and the popup is back.

Is there any other configuration to take care of?

Many thanks.

**Comment by feliche93** [comment]
@Vesli I face the same problem. Were you able to solve it?

**Comment by pablourkiza** [comment]
> Hi,
> 
> Thanks for this plugin ;)
> 
> On Safari / Chrome (iOS) or Android Chrome, I can click as many time as I want, the popup will always come back.
> 
> On the other hand, sometimes it won't show, I will wait 3min, reload the home page and the popup is back.
> 
> Is there any other configuration to take care of?
> 
> Many thanks.

Hello, the same here! How did you solve it? many thanks!

**Comment by piotrkilczuk** [comment]
v 2.2.0 fixed this hopefully. If not, feel free to reopen.

**Comment by pablourkiza** [comment]
Hello! Still not working :( I said it was the same in my case but it is not. What is happening in my case is that I cannot click on the button to hide the banner on Safari in iOS. It is working in android and also in desktop
