### ISSUE TITLE
KeyError when an exception is raised

### ISSUE THREAD

**Issue by JoseOrtiz** [TyMaszWeb/django-cookie-law#37]
When an exception is raised and the tag is rendered the request is not in context. Warning is displayed but I get a KeyError because of the code doesn't return or raise something.

**Comment by khink** [comment]
To be more precise (at least i think we're talking about the same thing), in https://github.com/TyMaszWeb/django-cookie-law/blob/master/cookielaw/templatetags/cookielaw_tags.py#L22 there is this code:
```python
if 'request' not in context:
    warnings.warn('No request object in context.'
                 'Are you sure you have django.core.context_processors.request enabled?')

if context['request'].COOKIES.get('cookielaw_accepted', False):
    return ''
```
This does not `return ''` after the warning, so the next line gives `KeyError: 'request'`.

I ran against this while running a test. When i add the `return ''`, my test continued and gave me the real error.

Would the maintainer(s) be willing to accept a PR for this?

**Comment by centralniak** [comment]
Of course, I'd love to see one.

**Comment by JoseOrtiz** [comment]
Yeah, that's the problem I saw @khink.
The problem is that you, @centralniak, made that line to be that way [here](https://github.com/TyMaszWeb/django-cookie-law/commit/941a3c3c5aa899e24cecf7c6a9fd65ecf2b663d4#diff-87a85c2e8e6fe39d736c20cf3e815d77), so I would like to know why you didn't finish the function after the warning properly

**Comment by centralniak** [comment]
I've probably made a mistake.
