### ISSUE TITLE
Django 2.2 compatible? OSError: [WinError 123] on Windows

### ISSUE THREAD

**Issue by FSE-DEV** [TyMaszWeb/django-cookie-law#48]
I used this on an older project running Django 2.1. Now, with a new project running Django 2.2 in a Windows environment, I get the following error after adding to installed apps: OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'

**Comment by centralniak** [comment]
Sorry, I haven't used Django recently and never used Django with Windows, so I won't be able to help.

Any luck debugging this?
