### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by dubirajara** [TyMaszWeb/django-cookie-law#56]
django-classy-tags is not compatible with Django 3.0 breaking the compatibility also of django-cookie-law. because six is no longer availiable in django.utils:  https://github.com/divio/django-classy-tags/issues/48

thank you

**Comment by superedo73** [comment]
I confirm the plugin does not work anymore on django 3.x

**Comment by piotrkilczuk** [comment]
It's very unlikely I'll find time to do this - but a pull request is more than welcome.

**Comment by michael93pl** [comment]
We probably need to wait untill django-classy-tags will merge newest pull requests fixing the issue of compatibility with Django 3.0

**Comment by maddrum** [comment]
django-classy-tags is taking time to be updated. Isn't it possible to be removed from this project?

**Comment by piotrkilczuk** [comment]
I'd be more than happy to have it removed.

**Comment by michael93pl** [comment]
It seems like django-classy-tags is somewhere close to get updated 
https://github.com/divio/django-classy-tags/issues/48

**Comment by dubirajara** [comment]
have merged but did not make the release 🤦‍♂️

**Comment by michael93pl** [comment]
@dubirajara yup, indeed ; / however, it shouldn't take too long I suppose

**Comment by michael93pl** [comment]
@dubirajara @piotrkilczuk django classy tags just has been released on pypi in version 1.0.0 with support of django 3.0
https://pypi.org/project/django-classy-tags/#description
