### ISSUE TITLE
Override translation

### ISSUE THREAD

**Issue by grondman** [TyMaszWeb/django-cookie-law#60]
Not sure if this is an issue for django-cookie-law or Django in general, but I'm totally at a loss here...

Problem:
- I'd like to edit some of the translations in django-cookie-law but despite adding translations for `COOKIE_INFO_HEADER` etc. to my own `.po` file (and running `compilemessages` of course, I keep seeing the translations that come with django-cookie-law.

I'm following the same procedure for editing Django admin translations and then it *does* work, so that makes the problem even more weird.

I could of course change the `COOKIE_INFO_HEADER`, etc. to something else and make translations for those, which would work, but then I lose the translations for other languages that come with the app and it's obviously a cumbersome solution to copy all those translations and re-tagging them with the new `msgid`s.

**Comment by grondman** [comment]
Still not solved, but I am on track of something: it turns out that overriding the translation does *not* work if my site is using `nl` as locale, but *does* work with `de`. I'll dig into this further...

**Comment by rob-vandam** [comment]
Have you read the solution here:
[](https://stackoverflow.com/questions/17837149/makemessages-for-an-app-installed-in-virtualenv)

**Comment by grondman** [comment]
> Have you read the solution here:
> https://stackoverflow.com/questions/17837149/makemessages-for-an-app-installed-in-virtualenv

I did. I turned StackOverflow inside out on this, but none of the solutions there - also the one you’re referring to - would explain why overriding `de` translations works and `nl` doesn’t.

**Comment by grondman** [comment]
Fixed my problem: the `django.po` supplied by the package did not have a `Plural-Forms` line at the top. Adding it resolved my issue. Created pull request #61 for this.

**Comment by grondman** [comment]
I guess we can close this one now that #61 is merged.
