### ISSUE TITLE
where to copy cookielaw.js

### ISSUE THREAD

**Issue by sarafv** [TyMaszWeb/django-cookie-law#67]
Hi, 
I don't understand what means "the markup" in the README.rst file, ie :
4. Add cookielaw/js/cookielaw.js to the markup
or 
To change the markup, just add a template named cookielaw/banner.html 

I'm using Django 2.2.9, my django app is called AtlasYEB, my project launchyeb and the templates are in templates/application

thanks!
Sara

**Comment by piotrkilczuk** [comment]
Hi Sara, 

Your markup is your HTML. You need to add that javascript there so it gets loaded.
