### ISSUE TITLE
Cookie “cookielaw_accepted” will be soon rejected

### ISSUE THREAD

**Issue by Andresmena99** [TyMaszWeb/django-cookie-law#68]
I am getting the following warning message when using Firefox:

Cookie “cookielaw_accepted” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

The error is apparently in this line in the JavaScript code:

document.cookie = name + "=" + value + expires + "; path=/";

Thanks in advance.

![2021-03-13_12-25](https://user-images.githubusercontent.com/38832393/111028523-764f4780-83f7-11eb-91bb-e4be253093f4.png)

**Comment by Andresmena99** [comment]
**Update**

This issue can be solved by simply changing the way the cookie is set, with the following line:

document.cookie = name + "=" + value + expires + ";path=/; Secure;";

**Comment by piotrkilczuk** [comment]
Would you mind opening a Pull Request @Andresmena99 ?

I'm not using this project currently, so I won't be able to verify it's working properly...
